// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About Page → Text Blurb 1*
 */
export interface AboutPageDocumentDataTextBlurb1Item {
	/**
	 * Title field in *About Page → Text Blurb 1*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_1[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Paragraph field in *About Page → Text Blurb 1*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_1[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Item in *About Page → Text Blurb 2*
 */
export interface AboutPageDocumentDataTextBlurb2Item {
	/**
	 * Title field in *About Page → Text Blurb 2*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_2[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Paragraph field in *About Page → Text Blurb 2*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_2[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Item in *About Page → Text Blurb 3*
 */
export interface AboutPageDocumentDataTextBlurb3Item {
	/**
	 * Title field in *About Page → Text Blurb 3*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_3[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Paragraph field in *About Page → Text Blurb 3*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_3[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Item in *About Page → Leadership*
 */
export interface AboutPageDocumentDataLeadershipItem {
	/**
	 * Headshot field in *About Page → Leadership*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.leadership[].headshot
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	headshot: prismic.ImageField<never>;
	
	/**
	 * Name field in *About Page → Leadership*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.leadership[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * Title field in *About Page → Leadership*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.leadership[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * Paragraph field in *About Page → Leadership*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.leadership[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
	/**
	 * Title Text field in *About Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.title_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title_text: prismic.TitleField;
	
	/**
	 * Featured Image field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	featured_image: prismic.ImageField<never>;
	
	/**
	 * Featured Image Caption field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.featured_image_caption
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	featured_image_caption: prismic.RichTextField;
	
	/**
	 * Text Blurb 1 field in *About Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_1[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb_1: prismic.GroupField<Simplify<AboutPageDocumentDataTextBlurb1Item>>;
	
	/**
	 * Grid Image 1 field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_1
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	grid_image_1: prismic.ImageField<never>;
	
	/**
	 * Grid Image 1 Caption field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_1_caption
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	grid_image_1_caption: prismic.RichTextField;
	
	/**
	 * Grid Image 2 field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_2
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	grid_image_2: prismic.ImageField<never>;
	
	/**
	 * Grid Image 2 Caption field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_2_caption
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	grid_image_2_caption: prismic.RichTextField;
	
	/**
	 * Grid Image 3 field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_3
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	grid_image_3: prismic.ImageField<never>;
	
	/**
	 * Grid Image 3 Caption field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_3_caption
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	grid_image_3_caption: prismic.RichTextField;
	
	/**
	 * Grid Image 4 field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_4
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	grid_image_4: prismic.ImageField<never>;
	
	/**
	 * Grid Image 4 Caption field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.grid_image_4_caption
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	grid_image_4_caption: prismic.RichTextField;
	
	/**
	 * Text Blurb 2 field in *About Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_2[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb_2: prismic.GroupField<Simplify<AboutPageDocumentDataTextBlurb2Item>>;
	
	/**
	 * Featured Image 2 field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.featured_image_2
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	featured_image_2: prismic.ImageField<never>;
	
	/**
	 * Featured Image 2 Caption field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.featured_image_2_caption
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	featured_image_2_caption: prismic.RichTextField;
	
	/**
	 * Text Blurb 3 field in *About Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.text_blurb_3[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb_3: prismic.GroupField<Simplify<AboutPageDocumentDataTextBlurb3Item>>;
	
	/**
	 * Leadership field in *About Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.leadership[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	leadership: prismic.GroupField<Simplify<AboutPageDocumentDataLeadershipItem>>;/**
	 * Meta Title field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<AboutPageDocumentData>, "about_page", Lang>;

/**
 * Item in *Additional Project → Images*
 */
export interface AdditionalProjectDocumentDataImagesItem {
	/**
	 * Image field in *Additional Project → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Content for Additional Project documents
 */
interface AdditionalProjectDocumentData {
	/**
	 * Sector field in *Additional Project*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.sector
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	sector: prismic.ContentRelationshipField<"sector">;
	
	/**
	 * Specialty field in *Additional Project*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.specialty
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	specialty: prismic.ContentRelationshipField<"specialty">;
	
	/**
	 * Name field in *Additional Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * Location field in *Additional Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	location: prismic.RichTextField;
	
	/**
	 * Sq Ft field in *Additional Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.sq_ft
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sq_ft: prismic.RichTextField;
	
	/**
	 * Client field in *Additional Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.client
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	client: prismic.RichTextField;
	
	/**
	 * Images field in *Additional Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: additional_project.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<AdditionalProjectDocumentDataImagesItem>>;
}

/**
 * Additional Project document from Prismic
 *
 * - **API ID**: `additional_project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AdditionalProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<AdditionalProjectDocumentData>, "additional_project", Lang>;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
	/**
	 * Title field in *Article*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Author field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	author: prismic.RichTextField;
	
	/**
	 * Published Date field in *Article*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.published_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	published_date: prismic.DateField;
	
	/**
	 * Hero Image field in *Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.hero_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hero_image: prismic.ImageField<never>;
	
	/**
	 * Hero Image Caption field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.hero_image_caption
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	hero_image_caption: prismic.RichTextField;
	
	/**
	 * Content field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;/**
	 * Meta Title field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, "article", Lang>;

/**
 * Item in *Careers Page → Architectural Team*
 */
export interface CareersPageDocumentDataArchitecturalTeamItem {
	/**
	 * Position field in *Careers Page → Architectural Team*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.architectural_team[].position
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	position: prismic.RichTextField;
	
	/**
	 * Location field in *Careers Page → Architectural Team*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.architectural_team[].location
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	location: prismic.RichTextField;
	
	/**
	 * Link field in *Careers Page → Architectural Team*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.architectural_team[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *Careers Page → Interior Design Team*
 */
export interface CareersPageDocumentDataInteriorDesignTeamItem {
	/**
	 * Position field in *Careers Page → Interior Design Team*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.interior_design_team[].position
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	position: prismic.RichTextField;
	
	/**
	 * Location field in *Careers Page → Interior Design Team*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.interior_design_team[].location
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	location: prismic.RichTextField;
	
	/**
	 * Link field in *Careers Page → Interior Design Team*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.interior_design_team[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for Careers Page documents
 */
interface CareersPageDocumentData {
	/**
	 * Headline field in *Careers Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.headline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.TitleField;
	
	/**
	 * Subheader field in *Careers Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.subheader
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subheader: prismic.TitleField;
	
	/**
	 * Featured Image field in *Careers Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	featured_image: prismic.ImageField<never>;
	
	/**
	 * Architectural Team field in *Careers Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.architectural_team[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	architectural_team: prismic.GroupField<Simplify<CareersPageDocumentDataArchitecturalTeamItem>>;
	
	/**
	 * Interior Design Team field in *Careers Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.interior_design_team[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	interior_design_team: prismic.GroupField<Simplify<CareersPageDocumentDataInteriorDesignTeamItem>>;
	
	/**
	 * Benefits field in *Careers Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.benefits
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	benefits: prismic.RichTextField;/**
	 * Meta Title field in *Careers Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Careers Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Careers Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Careers Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Careers Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: careers_page.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Careers Page document from Prismic
 *
 * - **API ID**: `careers_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CareersPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<CareersPageDocumentData>, "careers_page", Lang>;

/**
 * Content for Etc Page documents
 */
interface EtcPageDocumentData {
	/**
	 * Meta Title field in *Etc Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: etc_page.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Etc Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: etc_page.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Etc Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: etc_page.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Etc Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: etc_page.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Etc Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: etc_page.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Etc Page document from Prismic
 *
 * - **API ID**: `etc_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EtcPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<EtcPageDocumentData>, "etc_page", Lang>;

/**
 * Item in *Footer → Inquiries*
 */
export interface FooterDocumentDataInquiriesItem {
	/**
	 * Email field in *Footer → Inquiries*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.inquiries[].email
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	email: prismic.RichTextField;
	
	/**
	 * Phone field in *Footer → Inquiries*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.inquiries[].phone
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	phone: prismic.RichTextField;
}

/**
 * Item in *Footer → SLC HQ*
 */
export interface FooterDocumentDataSlcHqItem {
	/**
	 * Street field in *Footer → SLC HQ*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slc_hq[].street
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	street: prismic.RichTextField;
	
	/**
	 * City field in *Footer → SLC HQ*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slc_hq[].city
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	city: prismic.RichTextField;
}

/**
 * Item in *Footer → Careers*
 */
export interface FooterDocumentDataCareersItem {
	/**
	 * Text field in *Footer → Careers*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.careers[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Link field in *Footer → Careers*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.careers[].link
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link: prismic.RichTextField;
}

/**
 * Item in *Footer → STG*
 */
export interface FooterDocumentDataStgItem {
	/**
	 * Street field in *Footer → STG*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.stg[].street
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	street: prismic.RichTextField;
	
	/**
	 * City field in *Footer → STG*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.stg[].city
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	city: prismic.RichTextField;
}

/**
 * Item in *Footer → HI*
 */
export interface FooterDocumentDataHawaiiItem {
	/**
	 * Street field in *Footer → HI*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.hawaii[].street
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	street: prismic.RichTextField;
	
	/**
	 * City field in *Footer → HI*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.hawaii[].city
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	city: prismic.RichTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Heading field in *Footer*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
	
	/**
	 * Inquiries field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.inquiries[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	inquiries: prismic.GroupField<Simplify<FooterDocumentDataInquiriesItem>>;
	
	/**
	 * SLC HQ field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slc_hq[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	slc_hq: prismic.GroupField<Simplify<FooterDocumentDataSlcHqItem>>;
	
	/**
	 * Careers field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.careers[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	careers: prismic.GroupField<Simplify<FooterDocumentDataCareersItem>>;
	
	/**
	 * STG field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.stg[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	stg: prismic.GroupField<Simplify<FooterDocumentDataStgItem>>;
	
	/**
	 * HI field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.hawaii[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	hawaii: prismic.GroupField<Simplify<FooterDocumentDataHawaiiItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

/**
 * Item in *Homepage → Carousel*
 */
export interface HomepageDocumentDataCarouselItem {
	/**
	 * Image field in *Homepage → Carousel*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.carousel[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item in *Homepage → Text Blurb 1*
 */
export interface HomepageDocumentDataTextBlurb1Item {
	/**
	 * Title field in *Homepage → Text Blurb 1*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_1[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Paragraph field in *Homepage → Text Blurb 1*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_1[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
	
	/**
	 * Link field in *Homepage → Text Blurb 1*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_1[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Homepage → Text Blurb 1*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_1[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Item in *Homepage → Text Blurb 2*
 */
export interface HomepageDocumentDataTextBlurb2Item {
	/**
	 * Title field in *Homepage → Text Blurb 2*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_2[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Small Image field in *Homepage → Text Blurb 2*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_2[].small_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	small_image: prismic.ImageField<never>;
	
	/**
	 * Large Image field in *Homepage → Text Blurb 2*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_2[].large_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	large_image: prismic.ImageField<never>;
	
	/**
	 * Paragraph field in *Homepage → Text Blurb 2*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_2[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
	
	/**
	 * Link field in *Homepage → Text Blurb 2*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_2[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Homepage → Text Blurb 2*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_2[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Item in *Homepage → Text Blurb 3*
 */
export interface HomepageDocumentDataTextBlurb3Item {
	/**
	 * Full Width Image field in *Homepage → Text Blurb 3*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_3[].full_width_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	full_width_image: prismic.ImageField<never>;
	
	/**
	 * Title field in *Homepage → Text Blurb 3*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_3[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Link field in *Homepage → Text Blurb 3*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_3[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Homepage → Text Blurb 3*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_3[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Item in *Homepage → Text Blurb 4*
 */
export interface HomepageDocumentDataTextBlurb4Item {
	/**
	 * Title field in *Homepage → Text Blurb 4*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_4[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Paragraph field in *Homepage → Text Blurb 4*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_4[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
	
	/**
	 * Image field in *Homepage → Text Blurb 4*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_4[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Link field in *Homepage → Text Blurb 4*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_4[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Homepage → Text Blurb 4*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_4[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Heading field in *Homepage*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
	
	/**
	 * Carousel field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.carousel[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	carousel: prismic.GroupField<Simplify<HomepageDocumentDataCarouselItem>>;
	
	/**
	 * Text Blurb 1 field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_1[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb_1: prismic.GroupField<Simplify<HomepageDocumentDataTextBlurb1Item>>;
	
	/**
	 * Text Blurb 2 field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_2[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb_2: prismic.GroupField<Simplify<HomepageDocumentDataTextBlurb2Item>>;
	
	/**
	 * Text Blurb 3 field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_3[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb_3: prismic.GroupField<Simplify<HomepageDocumentDataTextBlurb3Item>>;
	
	/**
	 * Text Blurb 4 field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.text_blurb_4[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb_4: prismic.GroupField<Simplify<HomepageDocumentDataTextBlurb4Item>>;/**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Content for Position documents
 */
interface PositionDocumentData {
	/**
	 * Title field in *Position*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Team field in *Position*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.team
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	team: prismic.TitleField;
	
	/**
	 * Location field in *Position*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	location: prismic.TitleField;
	
	/**
	 * Description field in *Position*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;/**
	 * Meta Title field in *Position*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Position*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Position*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Position*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Position*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: position.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Position document from Prismic
 *
 * - **API ID**: `position`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PositionDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PositionDocumentData>, "position", Lang>;

/**
 * Item in *Project → Text Blurb*
 */
export interface ProjectDocumentDataTextBlurbItem {
	/**
	 * Heading field in *Project → Text Blurb*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.text_blurb[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Completed Date field in *Project → Text Blurb*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.text_blurb[].completed_date
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	completed_date: prismic.RichTextField;
	
	/**
	 * Paragraph field in *Project → Text Blurb*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.text_blurb[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Item in *Project → Image Carousel*
 */
export interface ProjectDocumentDataImageCarouselItem {
	/**
	 * Image field in *Project → Image Carousel*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.image_carousel[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item in *Project → Quote*
 */
export interface ProjectDocumentDataQuoteItem {
	/**
	 * Quote Text field in *Project → Quote*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.quote[].quote_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	quote_text: prismic.RichTextField;
	
	/**
	 * Source field in *Project → Quote*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.quote[].source
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	source: prismic.RichTextField;
}

/**
 * Item in *Project → Awards*
 */
export interface ProjectDocumentDataAwardsItem {
	/**
	 * Link field in *Project → Awards*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.awards[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Project → Awards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.awards[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Item in *Project → Publications*
 */
export interface ProjectDocumentDataPublicationsItem {
	/**
	 * Link field in *Project → Publications*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.publications[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Project → Publications*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.publications[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * Sector field in *Project*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.sector
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	sector: prismic.ContentRelationshipField<"sector">;
	
	/**
	 * Specialty field in *Project*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.specialty
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	specialty: prismic.ContentRelationshipField<"specialty">;
	
	/**
	 * Name field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * Client field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.client
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	client: prismic.RichTextField;
	
	/**
	 * Project Location field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.project_location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	project_location: prismic.RichTextField;
	
	/**
	 * Sq Ft field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.sq_ft
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sq_ft: prismic.RichTextField;
	
	/**
	 * Headline field in *Project*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.headline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.TitleField;
	
	/**
	 * Hero Image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.hero_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hero_image: prismic.ImageField<never>;
	
	/**
	 * Text Blurb field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.text_blurb[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_blurb: prismic.GroupField<Simplify<ProjectDocumentDataTextBlurbItem>>;
	
	/**
	 * Content Image 1 field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.content_image_1
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	content_image_1: prismic.ImageField<never>;
	
	/**
	 * Image Carousel field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.image_carousel[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	image_carousel: prismic.GroupField<Simplify<ProjectDocumentDataImageCarouselItem>>;
	
	/**
	 * Hero Image 2 field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.hero_image_2
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hero_image_2: prismic.ImageField<never>;
	
	/**
	 * Quote field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.quote[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	quote: prismic.GroupField<Simplify<ProjectDocumentDataQuoteItem>>;
	
	/**
	 * Awards field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.awards[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	awards: prismic.GroupField<Simplify<ProjectDocumentDataAwardsItem>>;
	
	/**
	 * Publications field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.publications[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	publications: prismic.GroupField<Simplify<ProjectDocumentDataPublicationsItem>>;
	
	/**
	 * Content Image 2 field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.content_image_2
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	content_image_2: prismic.ImageField<never>;
	
	/**
	 * Content Image 3 field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.content_image_3
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	content_image_3: prismic.ImageField<never>;
	
	/**
	 * Concluding Statement field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.concluding_statement
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	concluding_statement: prismic.RichTextField;/**
	 * Meta Title field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;

type ProjectsPageDocumentDataSlicesSlice = FeaturedProjectsSlice

/**
 * Content for Projects Page documents
 */
interface ProjectsPageDocumentData {
	/**
	 * Slice Zone field in *Projects Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ProjectsPageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Projects Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Projects Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Projects Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Projects Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Projects Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Projects Page document from Prismic
 *
 * - **API ID**: `projects_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ProjectsPageDocumentData>, "projects_page", Lang>;

type SectorDocumentDataSlicesSlice = SpecialtiesSlice

/**
 * Content for Sector documents
 */
interface SectorDocumentData {
	/**
	 * Order field in *Sector*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.order
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	order: prismic.NumberField;
	
	/**
	 * Name field in *Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * Description field in *Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * Slice Zone field in *Sector*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SectorDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Sector*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sector.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Sector document from Prismic
 *
 * - **API ID**: `sector`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SectorDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<SectorDocumentData>, "sector", Lang>;

/**
 * Item in *Services Page → Architecture*
 */
export interface ServicesPageDocumentDataArchitectureItem {
	/**
	 * Heading field in *Services Page → Architecture*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Services Page → Architecture*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[].sub_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sub_heading: prismic.TitleField;
	
	/**
	 * Text field in *Services Page → Architecture*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Image field in *Services Page → Architecture*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Image Caption field in *Services Page → Architecture*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[].image_caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	image_caption: prismic.RichTextField;
	
	/**
	 * Link field in *Services Page → Architecture*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Services Page → Architecture*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Item in *Services Page → Design*
 */
export interface ServicesPageDocumentDataDesignItem {
	/**
	 * Heading field in *Services Page → Design*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Services Page → Design*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].sub_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sub_heading: prismic.TitleField;
	
	/**
	 * Image 1 field in *Services Page → Design*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].image_1
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_1: prismic.ImageField<never>;
	
	/**
	 * Image 2 field in *Services Page → Design*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].image_2
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_2: prismic.ImageField<never>;
	
	/**
	 * Image Caption field in *Services Page → Design*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].image_caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	image_caption: prismic.RichTextField;
	
	/**
	 * Text field in *Services Page → Design*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Link field in *Services Page → Design*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Services Page → Design*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Item in *Services Page → Planning*
 */
export interface ServicesPageDocumentDataPlanningItem {
	/**
	 * Image field in *Services Page → Planning*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Image Caption field in *Services Page → Planning*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[].image_caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	image_caption: prismic.RichTextField;
	
	/**
	 * Heading field in *Services Page → Planning*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Services Page → Planning*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[].sub_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sub_heading: prismic.TitleField;
	
	/**
	 * Text field in *Services Page → Planning*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Link field in *Services Page → Planning*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Services Page → Planning*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Item in *Services Page → Sustainability*
 */
export interface ServicesPageDocumentDataSustainabilityItem {
	/**
	 * Image field in *Services Page → Sustainability*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Image Caption field in *Services Page → Sustainability*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[].image_caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	image_caption: prismic.RichTextField;
	
	/**
	 * Heading field in *Services Page → Sustainability*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Services Page → Sustainability*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[].sub_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sub_heading: prismic.TitleField;
	
	/**
	 * Text field in *Services Page → Sustainability*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Link field in *Services Page → Sustainability*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Services Page → Sustainability*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Content for Services Page documents
 */
interface ServicesPageDocumentData {
	/**
	 * Architecture field in *Services Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.architecture[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	architecture: prismic.GroupField<Simplify<ServicesPageDocumentDataArchitectureItem>>;
	
	/**
	 * Design field in *Services Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.design[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	design: prismic.GroupField<Simplify<ServicesPageDocumentDataDesignItem>>;
	
	/**
	 * Planning field in *Services Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.planning[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	planning: prismic.GroupField<Simplify<ServicesPageDocumentDataPlanningItem>>;
	
	/**
	 * Sustainability field in *Services Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.sustainability[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sustainability: prismic.GroupField<Simplify<ServicesPageDocumentDataSustainabilityItem>>;/**
	 * Meta Title field in *Services Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Services Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Services Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Services Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Services Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_page.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Services Page document from Prismic
 *
 * - **API ID**: `services_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ServicesPageDocumentData>, "services_page", Lang>;

/**
 * Content for Specialty documents
 */
interface SpecialtyDocumentData {
	/**
	 * Name field in *Specialty*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: specialty.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;/**
	 * Meta Title field in *Specialty*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: specialty.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_title: prismic.RichTextField;
	
	/**
	 * Meta Description field in *Specialty*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: specialty.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Title field in *Specialty*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: specialty.social_meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_title: prismic.RichTextField;
	
	/**
	 * Social Meta Description field in *Specialty*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: specialty.social_meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_meta_description: prismic.RichTextField;
	
	/**
	 * Social Meta Image field in *Specialty*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: specialty.social_meta_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	social_meta_image: prismic.ImageField<never>;
}

/**
 * Specialty document from Prismic
 *
 * - **API ID**: `specialty`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpecialtyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<SpecialtyDocumentData>, "specialty", Lang>;

/**
 * Item in *Team Page → Leadership*
 */
export interface TeamPageDocumentDataLeadershipItem {
	/**
	 * Headshot field in *Team Page → Leadership*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_page.leadership[].headshot
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	headshot: prismic.ImageField<never>;
	
	/**
	 * Name field in *Team Page → Leadership*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_page.leadership[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * Title field in *Team Page → Leadership*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_page.leadership[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * Paragraph field in *Team Page → Leadership*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_page.leadership[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

type TeamPageDocumentDataSlicesSlice = TeamSegmentSlice

/**
 * Content for Team Page documents
 */
interface TeamPageDocumentData {
	/**
	 * Leadership field in *Team Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_page.leadership[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	leadership: prismic.GroupField<Simplify<TeamPageDocumentDataLeadershipItem>>;
	
	/**
	 * Slice Zone field in *Team Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<TeamPageDocumentDataSlicesSlice>;
}

/**
 * Team Page document from Prismic
 *
 * - **API ID**: `team_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<TeamPageDocumentData>, "team_page", Lang>;

/**
 * Item in *Unlisted Page → Files*
 */
export interface UnlistedPageDocumentDataFilesItem {
	/**
	 * Image field in *Unlisted Page → Files*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.files[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Link field in *Unlisted Page → Files*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.files[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Title field in *Unlisted Page → Files*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.files[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Unlisted Page → Files*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.files[].sub_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sub_heading: prismic.RichTextField;
}

/**
 * Content for Unlisted Page documents
 */
interface UnlistedPageDocumentData {
	/**
	 * Heading field in *Unlisted Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Unlisted Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.sub_heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sub_heading: prismic.TitleField;
	
	/**
	 * Body field in *Unlisted Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
	
	/**
	 * Hero Image field in *Unlisted Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.hero_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hero_image: prismic.ImageField<never>;
	
	/**
	 * Publications Heading field in *Unlisted Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.publications_heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	publications_heading: prismic.TitleField;
	
	/**
	 * Publications Description field in *Unlisted Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.publications_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	publications_description: prismic.RichTextField;
	
	/**
	 * Files field in *Unlisted Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: unlisted_page.files[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	files: prismic.GroupField<Simplify<UnlistedPageDocumentDataFilesItem>>;
}

/**
 * Unlisted Page document from Prismic
 *
 * - **API ID**: `unlisted_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UnlistedPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<UnlistedPageDocumentData>, "unlisted_page", Lang>;

export type AllDocumentTypes = AboutPageDocument | AdditionalProjectDocument | ArticleDocument | CareersPageDocument | EtcPageDocument | FooterDocument | HomepageDocument | PositionDocument | ProjectDocument | ProjectsPageDocument | SectorDocument | ServicesPageDocument | SpecialtyDocument | TeamPageDocument | UnlistedPageDocument;

/**
 * Primary content in *FeaturedProjects → Items*
 */
export interface FeaturedProjectsSliceDefaultItem {
	/**
	 * Project field in *FeaturedProjects → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_projects.items[].project
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project: prismic.ContentRelationshipField<"project">;
}

/**
 * Default variation for FeaturedProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: FeaturedProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<FeaturedProjectsSliceDefaultItem>>;

/**
 * Slice variation for *FeaturedProjects*
 */
type FeaturedProjectsSliceVariation = FeaturedProjectsSliceDefault

/**
 * FeaturedProjects Shared Slice
 *
 * - **API ID**: `featured_projects`
 * - **Description**: FeaturedProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSlice = prismic.SharedSlice<"featured_projects", FeaturedProjectsSliceVariation>;

/**
 * Primary content in *Service → Primary*
 */
export interface ServiceSliceDefaultPrimary {
	/**
	 * Heading field in *Service → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Service → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * Text field in *Service → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Image field in *Service → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Link field in *Service → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Service → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Default variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServiceSliceDefaultPrimary>, never>;

/**
 * Primary content in *Service → Primary*
 */
export interface ServiceSliceDoubleImagePrimary {
	/**
	 * Heading field in *Service → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Sub Heading field in *Service → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * Text field in *Service → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Image 1 field in *Service → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.image_1
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_1: prismic.ImageField<never>;
	
	/**
	 * Image 2 field in *Service → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.image_2
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_2: prismic.ImageField<never>;
	
	/**
	 * Link field in *Service → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * Link Text field in *Service → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;
}

/**
 * Double Image variation for Service Slice
 *
 * - **API ID**: `doubleImage`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDoubleImage = prismic.SharedSliceVariation<"doubleImage", Simplify<ServiceSliceDoubleImagePrimary>, never>;

/**
 * Slice variation for *Service*
 */
type ServiceSliceVariation = ServiceSliceDefault | ServiceSliceDoubleImage

/**
 * Service Shared Slice
 *
 * - **API ID**: `service`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSlice = prismic.SharedSlice<"service", ServiceSliceVariation>;

/**
 * Primary content in *Specialties → Items*
 */
export interface SpecialtiesSliceDefaultItem {
	/**
	 * Specialty field in *Specialties → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: specialties.items[].specialty
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	specialty: prismic.ContentRelationshipField<"specialty">;
}

/**
 * Default variation for Specialties Slice
 *
 * - **API ID**: `default`
 * - **Description**: Specialties
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpecialtiesSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<SpecialtiesSliceDefaultItem>>;

/**
 * Slice variation for *Specialties*
 */
type SpecialtiesSliceVariation = SpecialtiesSliceDefault

/**
 * Specialties Shared Slice
 *
 * - **API ID**: `specialties`
 * - **Description**: Specialties
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpecialtiesSlice = prismic.SharedSlice<"specialties", SpecialtiesSliceVariation>;

/**
 * Primary content in *TeamSegment → Primary*
 */
export interface TeamSegmentSliceDefaultPrimary {
	/**
	 * Team Segment field in *TeamSegment → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_segment.primary.team_segment
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	team_segment: prismic.RichTextField;
}

/**
 * Primary content in *TeamSegment → Items*
 */
export interface TeamSegmentSliceDefaultItem {
	/**
	 * Headshot field in *TeamSegment → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_segment.items[].headshot
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	headshot: prismic.ImageField<never>;
	
	/**
	 * Name field in *TeamSegment → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_segment.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * Title field in *TeamSegment → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_segment.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Default variation for TeamSegment Slice
 *
 * - **API ID**: `default`
 * - **Description**: TeamSegment
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSegmentSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TeamSegmentSliceDefaultPrimary>, Simplify<TeamSegmentSliceDefaultItem>>;

/**
 * Slice variation for *TeamSegment*
 */
type TeamSegmentSliceVariation = TeamSegmentSliceDefault

/**
 * TeamSegment Shared Slice
 *
 * - **API ID**: `team_segment`
 * - **Description**: TeamSegment
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSegmentSlice = prismic.SharedSlice<"team_segment", TeamSegmentSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismicClient.ClientConfig): prismicClient.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			AboutPageDocument,
			AboutPageDocumentData,
			AdditionalProjectDocument,
			AdditionalProjectDocumentData,
			ArticleDocument,
			ArticleDocumentData,
			CareersPageDocument,
			CareersPageDocumentData,
			EtcPageDocument,
			EtcPageDocumentData,
			FooterDocument,
			FooterDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			PositionDocument,
			PositionDocumentData,
			ProjectDocument,
			ProjectDocumentData,
			ProjectsPageDocument,
			ProjectsPageDocumentData,
			SectorDocument,
			SectorDocumentData,
			ServicesPageDocument,
			ServicesPageDocumentData,
			SpecialtyDocument,
			SpecialtyDocumentData,
			TeamPageDocument,
			TeamPageDocumentData,
			UnlistedPageDocument,
			UnlistedPageDocumentData,
			AllDocumentTypes,
			FeaturedProjectsSlice,
			FeaturedProjectsSliceVariation,
			FeaturedProjectsSliceDefault,
			ServiceSlice,
			ServiceSliceVariation,
			ServiceSliceDefault,
			ServiceSliceDoubleImage,
			SpecialtiesSlice,
			SpecialtiesSliceVariation,
			SpecialtiesSliceDefault,
			TeamSegmentSlice,
			TeamSegmentSliceVariation,
			TeamSegmentSliceDefault
		}
	}
}