// Code generated by Slice Machine. DO NOT EDIT.

import FeaturedProjects from './FeaturedProjects';
import Specialties from './Specialties';

export {
	FeaturedProjects,
	Specialties,
};

export const components = {
	featured_projects: FeaturedProjects,
	specialties: Specialties,
};
