// Code generated by Slice Machine. DO NOT EDIT.

import FeaturedProjects from './FeaturedProjects';
import Service from './Service';
import Specialties from './Specialties';

export {
	FeaturedProjects,
	Service,
	Specialties,
};

export const components = {
	featured_projects: FeaturedProjects,
	service: Service,
	specialties: Specialties,
};
